name: Matrix Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
          os: [ubuntu-22.04]

        fail-fast: false

    steps:

    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: dependency (ubuntu)
      run: |
        sudo apt-get -q update
        sudo apt-get -qy install \
            curl build-essential make cmake libc6-dev \
            gcc g++ gfortran intel-mkl-full \
            python3 python3-pip python3-pytest \
            python3-numpy python3-scipy python3-pandas python3-matplotlib \
            jupyter
        cd /usr/bin ; sudo ln -sf py.test-3 py.test

    - name: dependency (custom)
      run: |
        export INSTALL_PREFIX=/usr
        ls -l .
        ls -l contrib
        sudo contrib/install.sh everything

    - name: Run tests
      run: |
        pytest test_Matrix.py
